COMPONENT = MalcodeAppC
CPU = -mmcu=msp430f1611
PFLAGS += -Os

PFLAGS += -DPARAMruns=$(PARAMruns)
PFLAGS += -DPARAMcaptures=$(PARAMcaptures)
PFLAGS += -DPARAMperiod=$(PARAMperiod)
PFLAGS += -DPARAMrg=$(PARAMrg)

PFLAGS += -DADDRtmp=$(ADDRtmp)
PFLAGS += -DADDRrestore=$(ADDRrestore)

PFLAGS += -DADDRse=$(ADDRse)
PFLAGS += -DADDRisri=$(ADDRisri)
PFLAGS += -DADDRst=$(ADDRst)
PFLAGS += -DADDRfe=$(ADDRfe)

include $(MAKERULES)
